name: healthka_drivers
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  provider: ^6.0.5
  permission_handler: ^10.2.0
  fluttertoast: ^8.2.1
  pinput: ^2.2.31
  google_fonts: ^4.0.3
  firebase_messaging: ^14.6.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.6
  flutter_polyline_points: ^1.0.0
  animated_text_kit: ^4.2.2
  sliding_up_panel: ^2.0.0+1
  web_socket_channel: ^2.4.0
  capped_progress_indicator: ^0.0.2
  image_picker: ^0.8.7+5
  image_cropper: ^4.0.1
  flutter_local_notifications: ^14.1.0
  flutter_callkit_incoming: ^2.0.0
  redis: ^3.1.0
  flutter_callkeep: ^0.3.2
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/car_android.png
    - assets/images/logo.png
    - assets/images/user_icon.png
    - assets/images/login.png
    - assets/images/otp2.png
    - assets/images/loading.gif

  fonts:
    - family: Brand-Bold
      fonts:
        - asset: assets/fonts/bolt-semibold.ttf
    - family: Brand-Regular
      fonts:
        - asset: assets/fonts/bolt-regular.ttf
